### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by dennypool** [arkangel-dev/BesiegeCreationImporter#19]
useless

**Comment by VerscheldeAlynne** [comment]
@dennypool that is neither a bug, nor a report, it is just well rude. what happened specifically? And why doesn't it work? What version of Blender did you use?

**Comment by arkangel-dev** [comment]
Ignore him. Odds are he didn't have the base game, so the addon didn't have a source to read the textures and models from. I've had a lot of people DM saying it doesn't work and turns out they don't have the game. But @dennypool If that is not the case, re-open the issue and elaborate with more than just the word "useless"

**Comment by dennypool** [comment]
> @dennypool that is neither a bug, nor a report, it is just well rude. what happened specifically? And why doesn't it work? What version of Blender did you use?

the addon doesn't have "import" button anymore, a guy write a comment under a youtube video and the creator reply "ehehehe" idk if is trolling or only stupid as fuck, btw  a import addon where you can't import nothing is useless no? 
btw i have the game from yeats, cost like 15$ ahahahahaah lol

**Comment by VerscheldeAlynne** [comment]
@dennypool Again, not a bug report, just a call out to someone on a youtube video, if  you really want to start a fight, pls don't do it here. However if you want to have a civil conversation, that is always possible. But not like this. 

Specifically for a bug report. 

-What machine are you on?
-What version of the game do you have?
-What version of blender do you have?
-What is the bug?
-How to reproduce the bug?

And finally, if you just saw it beneath a youtube video and didnt find it yourself, how do you even know it is a bug?

**Comment by arkangel-dev** [comment]
@dennypool Oh right. I remember you. Its a long story as to why I replied that. Send me the console log and I'll get on it asap. Really sorry about that. Also the import button will not appear if the .bsg file was not parsed properly. Can you try importing something simple like a single block maybe?

**Comment by arkangel-dev** [comment]
Since I haven't heard back, I'll just close this

**Comment by dennypool** [comment]
are you serious or some hard try troll? you remove the import function and
someone ask under the youtube video and you reply with "ehehe" or something
similar, LOl

Il giorno sab 9 apr 2022 alle ore 16:18 VerscheldeAlynne <
***@***.***> ha scritto:

**Comment by arkangel-dev** [comment]
Hi @dennypool . First off no one removed the import function. There are people other than who have used this addon and they haven't had any issues with it, and the code wasn't changed since then. Second off, I asked you for the console log, so I could help you and you didn't respond for 2 days, so I closed the issue. And now you come back, once again without the logs, calling @VerscheldeAlynne a troll. Please provide the console log so we can get this over with

**Comment by dennypool** [comment]
What?

Il giorno mar 11 ott 2022 alle 10:22 Sam Ramirez ***@***.***>
ha scritto:

**Comment by VerscheldeAlynne** [comment]
@dennypool 

Either pls provide actual info i.e. 

> -What machine are you on?
>-What version of the game do you have?
>-What version of blender do you have?
>-What is the bug?
>-How to reproduce the bug?

Otherwise pls leave

**Comment by dennypool** [comment]
Bruh, I don’t even know who you are and WHAT you want ahahahahahaha
besiege? Like the game? I don’t touch this game like from years!!! What are
you asking me? And who you are lol, it’s that some sort of joke? Wtf 😂😂😂

Il giorno mar 11 ott 2022 alle 15:55 VerscheldeAlynne <
***@***.***> ha scritto:

**Comment by arkangel-dev** [comment]
Ok, that's it. Im locking this thread.
